version: '3.8'

services:
  backend:
    build: ./backend
    networks:
      - backend
      - payment-processor
    environment:
      - GIN_MODE=release
      - DB_TYPE=sqlite
      - DB_PATH=/shared/payments.db
    volumes:
      - sqlite_data:/shared
    # depends_on:
    #   - payment-processor-default
    #   - payment-processor-fallback
    deploy:
      replicas: 3  # 3 instâncias do backend
      resources:
        limits:
          cpus: "0.45"
          memory: "110MB"

  # postgres:
  #   image: postgres:17-alpine
  #   container_name: rinha-postgres
  #   hostname: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=rinha_backend
  #   volumes:
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   networks:
  #     - backend
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.9"
  #         memory: "235MB"

  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    hostname: nginx
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf.multi:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - postgres
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

volumes:
  sqlite_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true 